# Generated by Django 4.1.3 on 2024-01-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori Başlığı')),
                ('slug', models.SlugField(unique=True, verbose_name='Kategori Slug')),
                ('genres', models.ManyToManyField(to='appMy.genre', verbose_name='Türler')),
            ],
        ),
    ]
