# Generated by Django 4.1.3 on 2024-01-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
