# Generated by Django 4.2.6 on 2024-01-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
